set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# Adjust this path to point to your MinGW-w64 installation
set(TOOLCHAIN_DIR "C:/msys64/mingw64/bin")

set(CMAKE_C_COMPILER "${TOOLCHAIN_DIR}/gcc.exe")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_DIR}/g++.exe")
set(CMAKE_MAKE_PROGRAM "${TOOLCHAIN_DIR}/mingw32-make.exe")

set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_DIR}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
